// src/svelte/LottiePlayer.svelte
<script lang="ts">
import { untrack } from "svelte";
import "../style/shimmer.scss";
import { buildShimmerMaskStyle } from "../main/shimmer.ts";
import {
	TLottie,
	type TLottieConfig,
	type TLottieEventPayload,
} from "../main/TLottie.ts";

interface Props extends Omit<TLottieConfig, "canvas"> {
	outline?: string;
	class?: string;
	/** When set, clicking the canvas calls `play()` — mainly useful for non-looping animations that should replay on click after completing. */
	playOnClick?: boolean;
	onLoad?: (payload: TLottieEventPayload) => void;
	onError?: (payload: TLottieEventPayload) => void;
	onComplete?: (payload: TLottieEventPayload) => void;
	lottieRefCallback?: (tlottie: TLottie | null) => void;
}

let {
	src,
	data,
	speed,
	loop,
	direction,
	autoplay,
	fitzModifier,
	layerColorReplacements,
	quality,
	workerCount,
	pool,
	forceRender,
	reportFrames,
	wasmUrl,
	outline,
	class: className,
	playOnClick,
	onLoad,
	onError,
	onComplete,
	lottieRefCallback,
}: Props = $props();

let canvasEl: HTMLCanvasElement | undefined = $state();
let loaded = $state(false);
let errored = $state(false);
let tlottie: TLottie | null = null;

// transferControlToOffscreen() can only run once per canvas element ever
// — {#key sourceKey} below tears down and recreates the <canvas> (a new
// element bound to canvasEl) whenever src/data identity changes, and
// this effect re-runs because it reads canvasEl. `untrack` keeps the
// other config fields from also being tracked here — otherwise every
// speed/loop/direction change would tear down and remount too, instead
// of applying live via the effects below.
const sourceKey = $derived(
	src !== undefined
		? `src:${src}`
		: typeof data === "string"
			? `data:${data}`
			: data !== undefined
				? "data:binary"
				: "empty",
);

$effect(() => {
	if (!canvasEl) return;
	const canvas = canvasEl;
	loaded = false;
	errored = false;

	tlottie = untrack(
		() =>
			new TLottie({
				canvas,
				src,
				data,
				speed,
				loop,
				direction,
				autoplay,
				fitzModifier,
				layerColorReplacements,
				quality,
				workerCount,
				pool,
				forceRender,
				reportFrames,
				wasmUrl,
			}),
	);
	lottieRefCallback?.(tlottie);

	const handleLoad = (payload: TLottieEventPayload) => {
		loaded = true;
		errored = false;
		onLoad?.(payload);
	};
	const handleError = (payload: TLottieEventPayload) => {
		errored = true;
		onError?.(payload);
	};
	const handleComplete = (payload: TLottieEventPayload) =>
		onComplete?.(payload);
	tlottie.on("load", handleLoad);
	tlottie.on("error", handleError);
	tlottie.on("complete", handleComplete);

	return () => {
		tlottie?.off("load", handleLoad);
		tlottie?.off("error", handleError);
		tlottie?.off("complete", handleComplete);
		lottieRefCallback?.(null);
		tlottie?.destroy();
		tlottie = null;
	};
});

// Playback tweaks apply live instead of tearing down and re-fetching.
$effect(() => {
	if (speed !== undefined) tlottie?.setSpeed(speed);
});
$effect(() => {
	if (loop !== undefined) tlottie?.setLoop(loop);
});
$effect(() => {
	if (direction !== undefined) tlottie?.setDirection(direction);
});
$effect(() => {
	if (fitzModifier !== undefined) tlottie?.setFitzModifier(fitzModifier);
});

const shimmerStyle = $derived(outline ? buildShimmerMaskStyle(outline) : null);

function onCanvasClick(): void {
	if (playOnClick) tlottie?.play();
}
</script>

<div class={className ? `tlottie-player ${className}` : "tlottie-player"}>
	{#key sourceKey}
		<canvas bind:this={canvasEl} class={loaded ? "tlottie-ready" : undefined} onclick={onCanvasClick}></canvas>
	{/key}
	{#if outline}
		<div class={!loaded || errored ? "tlottie-shimmer" : "tlottie-shimmer tlottie-hidden"} style:mask-image={shimmerStyle?.maskImage} style:-webkit-mask-image={shimmerStyle?.WebkitMaskImage}></div>
	{/if}
</div>

// src/solid/LottiePlayer.tsx
import {
	type ComponentProps,
	createEffect,
	createMemo,
	createSignal,
	type JSX,
	on,
	onCleanup,
	Show,
	splitProps,
} from "solid-js";
import "../style/shimmer.scss";
import { buildShimmerMaskStyle } from "../main/shimmer.ts";
import {
	TLottie,
	type TLottieConfig,
	type TLottieEventPayload,
} from "../main/TLottie.ts";

export interface LottiePlayerProps
	extends Omit<TLottieConfig, "canvas">,
		Omit<ComponentProps<"div">, "onLoad" | "onError"> {
	/** Raw SVG string used as a loading/error skeleton via CSS mask-image. */
	outline?: string;
	/** When set, clicking the canvas calls `play()` — mainly useful for non-looping animations that should replay on click after completing. */
	playOnClick?: boolean;
	onLoad?: (payload: TLottieEventPayload) => void;
	onError?: (payload: TLottieEventPayload) => void;
	onComplete?: (payload: TLottieEventPayload) => void;
	lottieRefCallback?: (tlottie: TLottie | null) => void;
}

const CONFIG_KEYS = [
	"src",
	"data",
	"speed",
	"loop",
	"direction",
	"autoplay",
	"fitzModifier",
	"layerColorReplacements",
	"quality",
	"workerCount",
	"pool",
	"forceRender",
	"reportFrames",
	"wasmUrl",
] as const;
const OWN_KEYS = [
	"outline",
	"playOnClick",
	"onLoad",
	"onError",
	"onComplete",
	"lottieRefCallback",
	"class",
	"classList",
] as const;

export function LottiePlayer(props: LottiePlayerProps): JSX.Element {
	const [config, own, rest] = splitProps(props, CONFIG_KEYS, OWN_KEYS);
	const [loaded, setLoaded] = createSignal(false);
	const [errored, setErrored] = createSignal(false);

	// transferControlToOffscreen() can only run once per canvas element ever
	// — <Show keyed> tears down and remounts its children (a fresh <canvas>,
	// re-running onMount) whenever src/data identity changes, instead of
	// reusing an already-transferred canvas.
	const sourceKey = createMemo(() =>
		config.src !== undefined
			? `src:${config.src}`
			: typeof config.data === "string"
				? `data:${config.data}`
				: config.data !== undefined
					? "data:binary"
					: "empty",
	);

	const shimmerStyle = () =>
		own.outline ? buildShimmerMaskStyle(own.outline) : null;

	return (
		<div
			class={own.class ? `tlottie-player ${own.class}` : "tlottie-player"}
			classList={own.classList}
			{...rest}
		>
			<Show when={sourceKey()} keyed>
				{(_key) => {
					let canvasEl!: HTMLCanvasElement;
					let tlottie: TLottie | null = null;

					const attach = (el: HTMLCanvasElement) => {
						canvasEl = el;
						setLoaded(false);
						setErrored(false);
						tlottie = new TLottie({ canvas: canvasEl, ...config });
						own.lottieRefCallback?.(tlottie);

						const handleLoad = (payload: TLottieEventPayload) => {
							setLoaded(true);
							setErrored(false);
							own.onLoad?.(payload);
						};
						const handleError = (payload: TLottieEventPayload) => {
							setErrored(true);
							own.onError?.(payload);
						};
						const handleComplete = (payload: TLottieEventPayload) =>
							own.onComplete?.(payload);
						tlottie.on("load", handleLoad);
						tlottie.on("error", handleError);
						tlottie.on("complete", handleComplete);

						onCleanup(() => {
							tlottie?.off("load", handleLoad);
							tlottie?.off("error", handleError);
							tlottie?.off("complete", handleComplete);
							own.lottieRefCallback?.(null);
							tlottie?.destroy();
							tlottie = null;
						});
					};

					// Playback tweaks apply live instead of tearing down and re-fetching.
					createEffect(
						on(
							() => config.speed,
							(speed) => {
								if (speed !== undefined) tlottie?.setSpeed(speed);
							},
							{ defer: true },
						),
					);
					createEffect(
						on(
							() => config.loop,
							(loop) => {
								if (loop !== undefined) tlottie?.setLoop(loop);
							},
							{ defer: true },
						),
					);
					createEffect(
						on(
							() => config.direction,
							(direction) => {
								if (direction !== undefined) tlottie?.setDirection(direction);
							},
							{ defer: true },
						),
					);
					createEffect(
						on(
							() => config.fitzModifier,
							(fitzModifier) => {
								if (fitzModifier !== undefined)
									tlottie?.setFitzModifier(fitzModifier);
							},
							{ defer: true },
						),
					);

					return (
						<canvas
							ref={attach}
							classList={{ "tlottie-ready": loaded() }}
							onClick={own.playOnClick ? () => tlottie?.play() : undefined}
						/>
					);
				}}
			</Show>
			<Show when={own.outline}>
				{(_outline) => (
					<div
						class="tlottie-shimmer"
						classList={{ "tlottie-hidden": loaded() && !errored() }}
						style={{
							"mask-image": shimmerStyle()?.maskImage,
							"-webkit-mask-image": shimmerStyle()?.WebkitMaskImage,
						}}
					/>
				)}
			</Show>
		</div>
	);
}
