// src/svelte/LottiePlayer.svelte
<script lang="ts">
import { untrack } from "svelte";
import "../style/shimmer.scss";
import { buildShimmerMaskStyle } from "../main/shimmer.ts";
import {
	TLottie,
	type TLottieConfig,
	type TLottieEventPayload,
} from "../main/TLottie.ts";

interface Props extends Omit<TLottieConfig, "canvas"> {
	outline?: string;
	class?: string;
	/** When set, clicking the canvas calls `play()` — mainly useful for non-looping animations that should replay on click after completing. */
	playOnClick?: boolean;
	onLoad?: (payload: TLottieEventPayload) => void;
	onError?: (payload: TLottieEventPayload) => void;
	onComplete?: (payload: TLottieEventPayload) => void;
	lottieRefCallback?: (tlottie: TLottie | null) => void;
}

let {
	src,
	data,
	speed,
	loop,
	direction,
	autoplay,
	fitzModifier,
	layerColorReplacements,
	quality,
	workerCount,
	pool,
	forceRender,
	reportFrames,
	wasmUrl,
	outline,
	class: className,
	playOnClick,
	onLoad,
	onError,
	onComplete,
	lottieRefCallback,
}: Props = $props();

let canvasEl: HTMLCanvasElement | undefined = $state();
let loaded = $state(false);
let errored = $state(false);
let tlottie: TLottie | null = null;

// transferControlToOffscreen() can only run once per canvas element ever
// — {#key sourceKey} below tears down and recreates the <canvas> (a new
// element bound to canvasEl) whenever src/data identity changes, and
// this effect re-runs because it reads canvasEl. `untrack` keeps the
// other config fields from also being tracked here — otherwise every
// speed/loop/direction change would tear down and remount too, instead
// of applying live via the effects below.
const sourceKey = $derived(
	src !== undefined
		? `src:${src}`
		: typeof data === "string"
			? `data:${data}`
			: data !== undefined
				? "data:binary"
				: "empty",
);

$effect(() => {
	if (!canvasEl) return;
	const canvas = canvasEl;
	loaded = false;
	errored = false;

	tlottie = untrack(
		() =>
			new TLottie({
				canvas,
				src,
				data,
				speed,
				loop,
				direction,
				autoplay,
				fitzModifier,
				layerColorReplacements,
				quality,
				workerCount,
				pool,
				forceRender,
				reportFrames,
				wasmUrl,
			}),
	);
	lottieRefCallback?.(tlottie);

	const handleLoad = (payload: TLottieEventPayload) => {
		loaded = true;
		errored = false;
		onLoad?.(payload);
	};
	const handleError = (payload: TLottieEventPayload) => {
		errored = true;
		onError?.(payload);
	};
	const handleComplete = (payload: TLottieEventPayload) =>
		onComplete?.(payload);
	tlottie.on("load", handleLoad);
	tlottie.on("error", handleError);
	tlottie.on("complete", handleComplete);

	return () => {
		tlottie?.off("load", handleLoad);
		tlottie?.off("error", handleError);
		tlottie?.off("complete", handleComplete);
		lottieRefCallback?.(null);
		tlottie?.destroy();
		tlottie = null;
	};
});

// Playback tweaks apply live instead of tearing down and re-fetching.
$effect(() => {
	if (speed !== undefined) tlottie?.setSpeed(speed);
});
$effect(() => {
	if (loop !== undefined) tlottie?.setLoop(loop);
});
$effect(() => {
	if (direction !== undefined) tlottie?.setDirection(direction);
});
$effect(() => {
	if (fitzModifier !== undefined) tlottie?.setFitzModifier(fitzModifier);
});

const shimmerStyle = $derived(outline ? buildShimmerMaskStyle(outline) : null);

function onCanvasClick(): void {
	if (playOnClick) tlottie?.play();
}
</script>

<div class={className ? `tlottie-player ${className}` : "tlottie-player"}>
	{#key sourceKey}
		<canvas bind:this={canvasEl} class={loaded ? "tlottie-ready" : undefined} onclick={onCanvasClick}></canvas>
	{/key}
	{#if outline}
		<div class={!loaded || errored ? "tlottie-shimmer" : "tlottie-shimmer tlottie-hidden"} style:mask-image={shimmerStyle?.maskImage} style:-webkit-mask-image={shimmerStyle?.WebkitMaskImage}></div>
	{/if}
</div>

// src/vue/LottiePlayer.vue
<script setup lang="ts">
import {
	computed,
	nextTick,
	onBeforeUnmount,
	onMounted,
	ref,
	shallowRef,
	watch,
} from "vue";
import "../style/shimmer.scss";
import type {
	FitzModifier,
	LayerColorReplacementInput,
	LoopConfig,
	PlayDirection,
	RenderQuality,
} from "../core/types.ts";
import { buildShimmerMaskStyle } from "../main/shimmer.ts";
import { TLottie, type TLottieEventPayload } from "../main/TLottie.ts";
import type { TLottieWorkerPool } from "../worker/pool.ts";

// Vue's `defineProps<T>()` macro resolves prop types by statically analyzing
// the interface — it can't follow a cross-file `Omit<TLottieConfig, ...>`
// generic, so the fields are spelled out flat here instead of extending
// TLottieConfig like the other framework adapters do.
export interface LottiePlayerProps {
	src?: string;
	data?: string | Uint8Array;
	speed?: number;
	loop?: LoopConfig;
	direction?: PlayDirection;
	autoplay?: boolean;
	fitzModifier?: FitzModifier;
	layerColorReplacements?: LayerColorReplacementInput[];
	quality?: Partial<RenderQuality>;
	wasmUrl?: string | URL;
	workerCount?: number;
	pool?: TLottieWorkerPool;
	forceRender?: boolean;
	reportFrames?: boolean;
	outline?: string;
	class?: string;
	/** When set, clicking the canvas calls `play()` — mainly useful for non-looping animations that should replay on click after completing. */
	playOnClick?: boolean;
}

const props = defineProps<LottiePlayerProps>();
const emit = defineEmits<{
	load: [payload: TLottieEventPayload];
	error: [payload: TLottieEventPayload];
	complete: [payload: TLottieEventPayload];
}>();
defineExpose({ tlottie: () => tlottieRef.value });

const canvasEl = ref<HTMLCanvasElement | null>(null);
const tlottieRef = shallowRef<TLottie | null>(null);
const loaded = ref(false);
const errored = ref(false);

// transferControlToOffscreen() can only run once per canvas element ever —
// keying the canvas on source identity forces Vue to replace the DOM node
// (instead of reusing an already-transferred one) whenever src/data
// changes, and the watcher below re-mounts TLottie against the new node.
const sourceKey = computed(() =>
	props.src !== undefined
		? `src:${props.src}`
		: typeof props.data === "string"
			? `data:${props.data}`
			: props.data !== undefined
				? "data:binary"
				: "empty",
);

let handleLoad: ((payload: TLottieEventPayload) => void) | null = null;
let handleError: ((payload: TLottieEventPayload) => void) | null = null;
let handleComplete: ((payload: TLottieEventPayload) => void) | null = null;

function mount(): void {
	if (!canvasEl.value) return;
	loaded.value = false;
	errored.value = false;
	const tlottie = new TLottie({
		canvas: canvasEl.value,
		src: props.src,
		data: props.data,
		speed: props.speed,
		loop: props.loop,
		direction: props.direction,
		autoplay: props.autoplay,
		fitzModifier: props.fitzModifier,
		layerColorReplacements: props.layerColorReplacements,
		quality: props.quality,
		workerCount: props.workerCount,
		pool: props.pool,
		forceRender: props.forceRender,
		reportFrames: props.reportFrames,
		wasmUrl: props.wasmUrl,
	});
	tlottieRef.value = tlottie;

	handleLoad = (payload) => {
		loaded.value = true;
		errored.value = false;
		emit("load", payload);
	};
	handleError = (payload) => {
		errored.value = true;
		emit("error", payload);
	};
	handleComplete = (payload) => emit("complete", payload);
	tlottie.on("load", handleLoad);
	tlottie.on("error", handleError);
	tlottie.on("complete", handleComplete);
}

function unmount(): void {
	const tlottie = tlottieRef.value;
	if (!tlottie) return;
	if (handleLoad) tlottie.off("load", handleLoad);
	if (handleError) tlottie.off("error", handleError);
	if (handleComplete) tlottie.off("complete", handleComplete);
	tlottie.destroy();
	tlottieRef.value = null;
}

onMounted(mount);
onBeforeUnmount(unmount);

watch(sourceKey, async () => {
	unmount();
	await nextTick(); // let the :key change replace the <canvas> element first
	mount();
});

// Playback tweaks apply live instead of tearing down and re-fetching.
watch(
	() => props.speed,
	(speed) => {
		if (speed !== undefined) tlottieRef.value?.setSpeed(speed);
	},
);
watch(
	() => props.loop,
	(loop) => {
		if (loop !== undefined) tlottieRef.value?.setLoop(loop);
	},
);
watch(
	() => props.direction,
	(direction) => {
		if (direction !== undefined) tlottieRef.value?.setDirection(direction);
	},
);
watch(
	() => props.fitzModifier,
	(fitzModifier) => {
		if (fitzModifier !== undefined)
			tlottieRef.value?.setFitzModifier(fitzModifier);
	},
);

const shimmerStyle = () =>
	props.outline ? buildShimmerMaskStyle(props.outline) : null;

function onCanvasClick(): void {
	if (props.playOnClick) tlottieRef.value?.play();
}
</script>

<template>
	<div :class="props.class ? `tlottie-player ${props.class}` : 'tlottie-player'">
		<canvas :key="sourceKey" ref="canvasEl" :class="{ 'tlottie-ready': loaded }" @click="onCanvasClick" />
		<div
			v-if="props.outline"
			class="tlottie-shimmer"
			:class="{ 'tlottie-hidden': loaded && !errored }"
			:style="{ maskImage: shimmerStyle()?.maskImage, WebkitMaskImage: shimmerStyle()?.WebkitMaskImage }"
		/>
	</div>
</template>
