// src/solid/LottiePlayer.tsx
import {
	type ComponentProps,
	createEffect,
	createMemo,
	createSignal,
	type JSX,
	on,
	onCleanup,
	Show,
	splitProps,
} from "solid-js";
import "../style/shimmer.scss";
import { buildShimmerMaskStyle } from "../main/shimmer.ts";
import {
	TLottie,
	type TLottieConfig,
	type TLottieEventPayload,
} from "../main/TLottie.ts";

export interface LottiePlayerProps
	extends Omit<TLottieConfig, "canvas">,
		Omit<ComponentProps<"div">, "onLoad" | "onError"> {
	/** Raw SVG string used as a loading/error skeleton via CSS mask-image. */
	outline?: string;
	/** When set, clicking the canvas calls `play()` — mainly useful for non-looping animations that should replay on click after completing. */
	playOnClick?: boolean;
	onLoad?: (payload: TLottieEventPayload) => void;
	onError?: (payload: TLottieEventPayload) => void;
	onComplete?: (payload: TLottieEventPayload) => void;
	lottieRefCallback?: (tlottie: TLottie | null) => void;
}

const CONFIG_KEYS = [
	"src",
	"data",
	"speed",
	"loop",
	"direction",
	"autoplay",
	"fitzModifier",
	"layerColorReplacements",
	"quality",
	"workerCount",
	"pool",
	"forceRender",
	"reportFrames",
	"wasmUrl",
] as const;
const OWN_KEYS = [
	"outline",
	"playOnClick",
	"onLoad",
	"onError",
	"onComplete",
	"lottieRefCallback",
	"class",
	"classList",
] as const;

export function LottiePlayer(props: LottiePlayerProps): JSX.Element {
	const [config, own, rest] = splitProps(props, CONFIG_KEYS, OWN_KEYS);
	const [loaded, setLoaded] = createSignal(false);
	const [errored, setErrored] = createSignal(false);

	// transferControlToOffscreen() can only run once per canvas element ever
	// — <Show keyed> tears down and remounts its children (a fresh <canvas>,
	// re-running onMount) whenever src/data identity changes, instead of
	// reusing an already-transferred canvas.
	const sourceKey = createMemo(() =>
		config.src !== undefined
			? `src:${config.src}`
			: typeof config.data === "string"
				? `data:${config.data}`
				: config.data !== undefined
					? "data:binary"
					: "empty",
	);

	const shimmerStyle = () =>
		own.outline ? buildShimmerMaskStyle(own.outline) : null;

	return (
		<div
			class={own.class ? `tlottie-player ${own.class}` : "tlottie-player"}
			classList={own.classList}
			{...rest}
		>
			<Show when={sourceKey()} keyed>
				{(_key) => {
					let canvasEl!: HTMLCanvasElement;
					let tlottie: TLottie | null = null;

					const attach = (el: HTMLCanvasElement) => {
						canvasEl = el;
						setLoaded(false);
						setErrored(false);
						tlottie = new TLottie({ canvas: canvasEl, ...config });
						own.lottieRefCallback?.(tlottie);

						const handleLoad = (payload: TLottieEventPayload) => {
							setLoaded(true);
							setErrored(false);
							own.onLoad?.(payload);
						};
						const handleError = (payload: TLottieEventPayload) => {
							setErrored(true);
							own.onError?.(payload);
						};
						const handleComplete = (payload: TLottieEventPayload) =>
							own.onComplete?.(payload);
						tlottie.on("load", handleLoad);
						tlottie.on("error", handleError);
						tlottie.on("complete", handleComplete);

						onCleanup(() => {
							tlottie?.off("load", handleLoad);
							tlottie?.off("error", handleError);
							tlottie?.off("complete", handleComplete);
							own.lottieRefCallback?.(null);
							tlottie?.destroy();
							tlottie = null;
						});
					};

					// Playback tweaks apply live instead of tearing down and re-fetching.
					createEffect(
						on(
							() => config.speed,
							(speed) => {
								if (speed !== undefined) tlottie?.setSpeed(speed);
							},
							{ defer: true },
						),
					);
					createEffect(
						on(
							() => config.loop,
							(loop) => {
								if (loop !== undefined) tlottie?.setLoop(loop);
							},
							{ defer: true },
						),
					);
					createEffect(
						on(
							() => config.direction,
							(direction) => {
								if (direction !== undefined) tlottie?.setDirection(direction);
							},
							{ defer: true },
						),
					);
					createEffect(
						on(
							() => config.fitzModifier,
							(fitzModifier) => {
								if (fitzModifier !== undefined)
									tlottie?.setFitzModifier(fitzModifier);
							},
							{ defer: true },
						),
					);

					return (
						<canvas
							ref={attach}
							classList={{ "tlottie-ready": loaded() }}
							onClick={own.playOnClick ? () => tlottie?.play() : undefined}
						/>
					);
				}}
			</Show>
			<Show when={own.outline}>
				{(_outline) => (
					<div
						class="tlottie-shimmer"
						classList={{ "tlottie-hidden": loaded() && !errored() }}
						style={{
							"mask-image": shimmerStyle()?.maskImage,
							"-webkit-mask-image": shimmerStyle()?.WebkitMaskImage,
						}}
					/>
				)}
			</Show>
		</div>
	);
}

// src/react/LottiePlayer.tsx
import { type HTMLAttributes, useEffect, useRef, useState } from "react";
import "../style/shimmer.scss";
import { buildShimmerMaskStyle } from "../main/shimmer.ts";
import {
	TLottie,
	type TLottieConfig,
	type TLottieEventPayload,
} from "../main/TLottie.ts";

export interface LottiePlayerProps
	extends Omit<TLottieConfig, "canvas">,
		Omit<HTMLAttributes<HTMLDivElement>, "onLoad" | "onError"> {
	/** Raw SVG string used as a loading/error skeleton via CSS mask-image. */
	outline?: string;
	/** When set, clicking the canvas calls `play()` — mainly useful for non-looping animations that should replay on click after completing. */
	playOnClick?: boolean;
	onLoad?: (payload: TLottieEventPayload) => void;
	onError?: (payload: TLottieEventPayload) => void;
	onComplete?: (payload: TLottieEventPayload) => void;
	lottieRefCallback?: (tlottie: TLottie | null) => void;
}

export function LottiePlayer(props: LottiePlayerProps) {
	const {
		src,
		data,
		speed,
		loop,
		direction,
		autoplay,
		fitzModifier,
		layerColorReplacements,
		quality,
		workerCount,
		pool,
		forceRender,
		reportFrames,
		wasmUrl,
		outline,
		playOnClick,
		onLoad,
		onError,
		onComplete,
		lottieRefCallback,
		className,
		...rest
	} = props;

	const canvasRef = useRef<HTMLCanvasElement>(null);
	const tlottieRef = useRef<TLottie | null>(null);
	const [loaded, setLoaded] = useState(false);
	const [errored, setErrored] = useState(false);

	// Only src/data identity changes tear down and re-fetch/re-parse the
	// animation; playback tweaks below are applied live to the running
	// instance instead, since they're cheap and shouldn't restart playback.
	useEffect(() => {
		const canvas = canvasRef.current;
		if (!canvas) return;
		setLoaded(false);
		setErrored(false);

		const tlottie = new TLottie({
			canvas,
			src,
			data,
			speed,
			loop,
			direction,
			autoplay,
			fitzModifier,
			layerColorReplacements,
			quality,
			workerCount,
			pool,
			forceRender,
			reportFrames,
			wasmUrl,
		});
		tlottieRef.current = tlottie;
		lottieRefCallback?.(tlottie);

		const handleLoad = (payload: TLottieEventPayload) => {
			setLoaded(true);
			setErrored(false);
			onLoad?.(payload);
		};
		const handleError = (payload: TLottieEventPayload) => {
			setErrored(true);
			onError?.(payload);
		};
		const handleComplete = (payload: TLottieEventPayload) =>
			onComplete?.(payload);
		tlottie.on("load", handleLoad);
		tlottie.on("error", handleError);
		tlottie.on("complete", handleComplete);

		return () => {
			tlottie.off("load", handleLoad);
			tlottie.off("error", handleError);
			tlottie.off("complete", handleComplete);
			tlottieRef.current = null;
			lottieRefCallback?.(null);
			tlottie.destroy();
		};
	}, [src, data]);

	useEffect(() => {
		if (speed !== undefined) tlottieRef.current?.setSpeed(speed);
	}, [speed]);
	useEffect(() => {
		if (loop !== undefined) tlottieRef.current?.setLoop(loop);
	}, [loop]);
	useEffect(() => {
		if (direction !== undefined) tlottieRef.current?.setDirection(direction);
	}, [direction]);
	useEffect(() => {
		if (fitzModifier !== undefined)
			tlottieRef.current?.setFitzModifier(fitzModifier);
	}, [fitzModifier]);

	const shimmerStyle = outline ? buildShimmerMaskStyle(outline) : null;

	return (
		<div
			className={className ? `tlottie-player ${className}` : "tlottie-player"}
			{...rest}
		>
			<canvas
				// transferControlToOffscreen() can only run once per canvas
				// element ever — keying on source identity forces React to
				// mount a fresh <canvas> instead of reusing the old
				// (already-transferred) one when src/data changes.
				key={reactKeyForSource(src, data)}
				ref={canvasRef}
				className={loaded ? "tlottie-ready" : undefined}
				onClick={playOnClick ? () => tlottieRef.current?.play() : undefined}
			/>
			{outline ? (
				<div
					className={
						!loaded || errored
							? "tlottie-shimmer"
							: "tlottie-shimmer tlottie-hidden"
					}
					style={{
						maskImage: shimmerStyle?.maskImage,
						WebkitMaskImage: shimmerStyle?.WebkitMaskImage,
					}}
				/>
			) : null}
		</div>
	);
}

function reactKeyForSource(
	src: string | undefined,
	data: string | Uint8Array | undefined,
): string {
	if (src !== undefined) return `src:${src}`;
	if (typeof data === "string") return `data:${data}`;
	return data !== undefined ? "data:binary" : "empty";
}
